### ISSUE TITLE
[RFE] support xz compressed comps.xml

### ISSUE THREAD

**Issue by mattiaverga** [rpm-software-management/libcomps#103]
It seems createrepo_c version 1.x defaults to XZ compress comps.xml also.
I tried to use something like:
```
                    if repo_info['group'].endswith('xz'):
                        xml_content = lzma.open(repo_info['group']).read()
>                       ret = comps.fromxml_f(xml_content)
E                       TypeError: function accept string and optional xml_options dict
```

Is there a clever way to make this work?
https://github.com/fedora-infra/bodhi/pull/5455

**Comment by kontura** [comment]
I think `createrepo_c-1.0.0-1.fc39.x86_64` should default to `zstd` even for comps.

Nonetheless you can do:
```python
xml_content = lzma.open("./comps.xml.xz").read()
ret = comps.fromxml_str(xml_content.decode())

```

**Comment by j-mracek** [comment]
I also think that createrepo_c should have the same default for all types of metadata types.

**Comment by mattiaverga** [comment]
Oh, yes, [bodhi tests](https://github.com/fedora-infra/bodhi/blob/94a44c46afa0a988509d88ea9e754ab9ae41f1f4/bodhi-server/tests/base.py#L525-L529) create repo with `--xz`, so they override the default compression.
However it seems before createrepo_c v1.x the comps.xml file was not compressed and just plain xml.

The above suggested solution
`ret = comps.fromxml_str(xml_content.decode())`
works when everything it's ok, but seems to not behave as expected when the content of comps.xml is invalid, returning a bad crash as `Fatal Python error: Segmentation fault` instead of raising an Exception, for example in [this test](https://github.com/fedora-infra/bodhi/blob/94a44c46afa0a988509d88ea9e754ab9ae41f1f4/bodhi-server/tests/test_util.py#L479C12-L488):
https://github.com/fedora-infra/bodhi/actions/runs/5935123593/job/16093069432?pr=5455

**Comment by kontura** [comment]
I made a PR to fix the crash: https://github.com/rpm-software-management/libcomps/pull/104

**Comment by mattiaverga** [comment]
I've tested the above patch and now the [test](https://github.com/fedora-infra/bodhi/blob/f05e8281a3aaa91b8c6cb8685dd1148af0fe441f/bodhi-server/tests/test_util.py#L479-L488) that previously crashed completes well.
However, I now get [another segfault](https://github.com/fedora-infra/bodhi/actions/runs/6093397011/job/16543726551) in the following [test](https://github.com/fedora-infra/bodhi/blob/f05e8281a3aaa91b8c6cb8685dd1148af0fe441f/bodhi-server/tests/test_util.py#L490-L499) which is slightly different in what wrong content is passed in comps.xml.

**Comment by dralley** [comment]
Note that this isn't a fully new issue.  Libcomps isn't very robust to invalid inputs https://github.com/rpm-software-management/libcomps/issues/47

**Comment by kontura** [comment]
I have created another PR to patch some of the holes: https://github.com/rpm-software-management/libcomps/pull/106
But yea there is likely more.
