### ISSUE TITLE
FNM_CASEFOLD flag is not supported in AIX

### ISSUE THREAD

**Issue by sumitradawn** [rpm-software-management/libcomps#113]
Hello  Community members,

In AIX it seems fnmatch() function doesn't have FNM_CASEFOLD flag. 
https://www.ibm.com/docs/en/aix/7.2?topic=f-fnmatch-subroutine

Hence, if one try to compile libcomps with FNM_CASEFOLD flag enabled then we can see below compilation error.

```

error: 'FNM_CASEFOLD' undeclared (first use in this function)
 1107 |     PyModule_AddIntConstant(m, "MATCH_IGNORECASE", FNM_CASEFOLD);
      |                                                    ^~~~~~~~~~~~

```
We can pass 0 value instead of passing FNM_CASEFOLD to resolve the compilation error.

Please have a look into the attached patch and provide your comments/suggestions.
[libcomps-0.1.21-remove-FNM_CASEFOLD.patch](https://github.com/user-attachments/files/16961691/libcomps-0.1.21-remove-FNM_CASEFOLD.patch)

**Comment by jan-kolarik** [comment]
Hi @sumitradawn, we prefer to keep our stack portable. As with other components like `libdnf`, `dnf5`, and `libsolv`, we do not support non-standard systems lacking the `FNM_CASEFOLD` flag. The only solution for building `libcomps` on AIX would be to maintain a downstream patch with your proposed changes.
