### ISSUE TITLE
GLib dependency

### ISSUE THREAD

**Issue by cgwalters** [rpm-software-management/libcomps#22]
Hi...I was looking at using libcomps in the Atomic/rpm-ostree project ( https://github.com/projectatomic/rpm-ostree ), and reading the libcomps API, I have to wonder: what do you think about a GLib dependency?

librepo has one now.  It's widely available, and helps you avoid custom data types for basic things like linked lists.

**Comment by cgwalters** [comment]
Two years later, let's look at options.

Are there active RHEL-6 consumers still?

One option is to keep the current libcomps as is, but only do security updates.  Then fork the code and merge it into the new libhif core, similarly to what has been done with hawkey.

**Comment by kontura** [comment]
I don't want to introduce glib dependency here or do any bigger rewrites because of it.
