### ISSUE TITLE
Incorrect (fully-versioned) SOVERSION in SONAME

### ISSUE THREAD

**Issue by Ionic** [rpm-software-management/libcomps#51]
Currently, `libcomps` uses the full version number as its `SOVERSION` in the `SONAME`.

For example, currently, libcomps.so has its `SONAME` set to `libcomps.so.0.1.11`.

I think I don't have to educate you on why that's a bad idea and what the `SONAME`/`SOVERSION` should actually be used for, because ironically you already have a library version in place at [libcomps/version.cmake](https://github.com/rpm-software-management/libcomps/blob/master/libcomps/version.cmake.in) - you're [just not using it](https://github.com/rpm-software-management/libcomps/blob/master/libcomps/src/CMakeLists.txt#L50).

I strongly believe that the `set_target_properties` call should be using either `${libcomps_RELEASE}`, `${libcomps_VERSION_MAJOR}`, or possibly `${libcomps_VERSION_MINOR}` instead of `${VERSION}`.

---

Before doing so, note, however, that there are two more problems that should probably be fixed first:
  1) you have two diverging copies of `version.cmake{,.in}` at [/version.cmake](https://github.com/rpm-software-management/libcomps/blob/master/version.cmake) and [/libcomps/version.cmake](https://github.com/rpm-software-management/libcomps/blob/master/libcomps/version.cmake). There should likely only be one. Since [ver-bump.py](https://github.com/rpm-software-management/libcomps/blob/master/ver-bump.py#L31-L37) updates only `libcomps/version.cmake` and uses `libcomps/version.cmake.in` as its template, the top-level files should probably be deleted. Be careful with blind deletions, though, since the top-level file sets `libcomps_RELEASE` to `4`, while the `libcomps`-sub-directory-based one sets the variable to `1`. I don't know which is the correct one, because...
  2) [ver-bump.py](https://github.com/rpm-software-management/libcomps/blob/master/ver-bump.py) looks either broken or `${libcomps_RELEASE}` is a useless number without a clear concept. Note how this variable is always reset to `1`, but never incremented or changed in any other way. You didn't document its semantic meaning anywhere, so I don't know what it is supposed to represent. If there really is no semantic meaning to it, just drop it.

**Comment by Conan-Kudo** [comment]
@Ionic I think it probably makes sense to set it to `VERSION_MAJOR`.

**Comment by j-mracek** [comment]
I would recommend to set it to "0.1.11" (just to freeze it). At the time when the SO name change will be required we can set something more resonable.

**Comment by Conan-Kudo** [comment]
This is now fixed in the 0.1.14 release. I decided to do one last "break" and switch it to just have the somajor.
