### ISSUE TITLE
Segfault for empty DictStr when converted to string

### ISSUE THREAD

**Issue by CodeHeeler** [rpm-software-management/libcomps#54]
Calling str() on empty DictStr object triggers a segfault.

Can reproduce with this code:

```python
import libcomps
import urllib.request

url_empty_strdict = 'https://repos.fedorapeople.org/pulp/pulp/fixtures/rpm-unsigned/repodata/5e655c4cde94fe5f1a39ed2015d5a5bbfa051fa032b3fb911609ada337b5fee8-comps.xml'
url_non_empty_strdict = 'https://dl.fedoraproject.org/pub/epel/7/x86_64/repodata/c629c8fc439517aed1ff09d9c8ba32f2fa6984a2f9683e4cd19726591f68128b-comps-Everything.x86_64.xml'

def test(url):
    file_path = '/tmp/test_comps.xml'
    urllib.request.urlretrieve(url, file_path)
    comps = libcomps.Comps()
    comps.fromxml_f(file_path)
    print(comps.categories[0].desc_by_lang)

test(url_empty_strdict)  # segfault
#test(url_non_empty_strdict) # no segfault

```

We are using the python bindings, so not sure if it goes beyond that.

Versions in use:

$ sudo dnf list installed | grep libcomps
libcomps.x86_64                      0.1.11-1.fc30                          @anaconda       
libcomps-devel.x86_64                0.1.11-1.fc30                          @fedora         
python3-libcomps.x86_64              0.1.11-1.fc30                          @anaconda

**Comment by dralley** [comment]
Looks like this should be closed, fixed by https://github.com/rpm-software-management/libcomps/pull/56/
